pipeline {
    agent any
    stages {
        stage('Deploy Vault') {
            steps {
                dir('applications/vault') {
                    sh 'ansible-playbook -i inventory deploy_vault.yml'
                }
            }
        }
    }
}
