pipeline {
    agent any
    stages {
        stage('Deploy WebMethods') {
            steps {
                dir('applications/webmethods') {
                    sh 'ansible-playbook -i inventory deploy_webmethods.yml'
                }
            }
        }
    }
}
