pipeline {
    agent any
    stages {
        stage('Deploy webMethods IS') {
            steps {
                sshagent(['32_creds']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no root@10.10.20.32 'cd /opt/dsp_automation/webmethods_deploy && ansible-playbook -i inventory deploy_webmethods.yml'
                    '''
                }
            }
        }
    }
}
