pipeline {
    agent any
    stages {
        stage('Deploy MinIO') {
            steps {
                dir('applications/minio') {
                    sh 'ansible-playbook -i inventory deploy_minio.yml'
                }
            }
        }
    }
}
