pipeline {
    agent any
    stages {
        stage('Deploy Confluent Flink') {
            steps {
                dir('applications/confluentflink') {
                    sh 'ansible-playbook -i inventory deploy_confluentflink.yml'
                }
            }
        }
    }
}
