pipeline {
    agent any
    stages {
        stage('Deploy IBMMQ') {
            steps {
                sshagent(['32_creds']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no root@10.10.20.32 'cd /opt/Docker_Databases/applications/ibmmq && ansible-playbook -i inventory deploy_ibmmq.yml'
                    '''
                }
            }
        }
    }
}
