pipeline {
    agent any
    stages {
        stage('Deploy ClickHouse') {
            steps {
                dir('applications/clickhouse') {
                    sh 'ansible-playbook -i inventory deploy_clickhouse.yml'
                }
            }
        }
    }
}
